services:
  geth:
    image: ethereum/client-go
    container_name: geth
    ports:
    - 8545:8545
    - 30303:30303
    command: --dev --http --http.addr 0.0.0.0 --http.api eth,net,web3,personal,miner,txpool
      --http.corsdomain=* --http.vhosts=* --allow-insecure-unlock
    networks:
    - carros_net
    healthcheck:
      test:
      - CMD
      - wget
      - --quiet
      - --tries=1
      - --spider
      - http://localhost:8545
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  contract_deploy:
    build:
      context: .
    command: python blockchain/deploy_contract.py
    container_name: contract_deploy
    networks:
    - carros_net
    depends_on:
      geth:
        condition: service_healthy
    environment:
    - PRIVATE_KEY=142f5185f1474cbac187d772a6db128d895de4e1aee7141249d550c944bb8ecb
    - ETH_NODE_URL=http://geth:8545
    volumes:
    - ./blockchain:/app/blockchain
  server_a:
    build:
      context: .
    command: python servers/server_a.py
    container_name: server_a
    ports:
    - 5000:5000
    networks:
    - carros_net
    environment:
    - CONTRACT_ADDRESS=0xDc429D726965f9790028E5628ce6d39BB070BBCc
    - PRIVATE_KEY=564847811f5a439c429afca364edaff8c316ea3f5227f2fce4a7d344a114c6ac
    - ETH_NODE_URL=http://geth:8545
    depends_on:
      contract_deploy:
        condition: service_completed_successfully
    volumes:
    - ./blockchain:/app/blockchain
  server_b:
    build:
      context: .
    command: python servers/server_b.py
    container_name: server_b
    ports:
    - 5001:5001
    networks:
    - carros_net
    environment:
    - CONTRACT_ADDRESS=0x6E87D8adcAB4ad899001333Dc5238b612f24e178
    - PRIVATE_KEY=8c2a27ca990041e153d2a00e7ac54ea17579167aad94dd749581ca3262e3db6e
    - ETH_NODE_URL=http://geth:8545
    depends_on:
      contract_deploy:
        condition: service_completed_successfully
    volumes:
    - ./blockchain:/app/blockchain
  server_c:
    build:
      context: .
    command: python servers/server_c.py
    container_name: server_c
    ports:
    - 5002:5002
    networks:
    - carros_net
    environment:
    - CONTRACT_ADDRESS=0x5069aC274d2Fd8940463299b9e737daEbB4C2C90
    - PRIVATE_KEY=e0a4cb5b3145524fc18cd776e91526120d6b070d30fa07e41768ea312657dbd6
    - ETH_NODE_URL=http://geth:8545
    depends_on:
      contract_deploy:
        condition: service_completed_successfully
    volumes:
    - ./blockchain:/app/blockchain
  server_d:
    build:
      context: .
    command: python servers/server_d.py
    container_name: server_d
    ports:
    - 5003:5003
    networks:
    - carros_net
    environment:
    - CONTRACT_ADDRESS=0xd536f138f3968e9257AF7258e15e82579a043fA2
    - PRIVATE_KEY=3d93a3778ec083ae33a5449da2f67ed7f554cb00d1ca4658dd12ce733106a2ca
    - ETH_NODE_URL=http://geth:8545
    depends_on:
      contract_deploy:
        condition: service_completed_successfully
    volumes:
    - ./blockchain:/app/blockchain
  server_e:
    build:
      context: .
    command: python servers/server_e.py
    container_name: server_e
    ports:
    - 5004:5004
    networks:
    - carros_net
    environment:
    - CONTRACT_ADDRESS=0x7F94aC738b21fbA8391637a82115B28A118228dC
    - PRIVATE_KEY=bbbe1f1738337f73cdf7d51948acf11af7b78ad63c391f9b7441d9abed10ac27
    - ETH_NODE_URL=http://geth:8545
    depends_on:
      contract_deploy:
        condition: service_completed_successfully
    volumes:
    - ./blockchain:/app/blockchain
  transactions_api:
    build:
      context: .
    command: python transactions.py
    container_name: transactions_api
    ports:
    - 5100:5100
    networks:
    - carros_net
    depends_on:
      contract_deploy:
        condition: service_completed_successfully
    environment:
    - CONTRACT_ADDRESS=None
    - ETH_NODE_URL=http://geth:8545
    volumes:
    - ./blockchain:/app/blockchain
networks:
  carros_net:
    driver: bridge
