FROM alpine:latest

# Instala o Mosquitto
RUN apk add --no-cache mosquitto

# Define o diretório de trabalho
WORKDIR /mosquitto

# Copia o arquivo de configuração e os diretórios
COPY mosquitto/config/mosquitto.conf ./config/
COPY mosquitto/data/ ./data/
COPY mosquitto/log/ ./log/

# Expõe a porta configurada no mosquitto.conf (18833)
EXPOSE 18833

# Define o usuário Mosquitto
USER mosquitto

# Comando para iniciar o Mosquitto com o arquivo de configuração
CMD ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
# CRIAR: 
# docker build -f Dockerfile.mosquitto -t mosquitto-custom .
# RODAR: 
# docker run -d -p 18833:18833 -v $(pwd)/mosquitto/data:/mosquitto/data -v $(pwd)/mosquitto/log:/mosquitto/log --name mosquitto-custom mosquitto-custom