
services:
  nuvem:
    build: .
    container_name: nuvem
    ports:
      - "5000:5000"
    environment:
      - DOCKER_ENV=true
      - NUM_PONTOS=400
    networks:
      - rede_recarga
    volumes:
      - .:/app
    command: ["python", "./nuvem.py"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  ponto:
    build: .
    environment:
      - DOCKER_ENV=true
      - PONTO_ID={{.Task.Slot}}
      - PORT=$((6000 + {{.Task.Slot}}))
    networks:
      - rede_recarga
    volumes:
      - .:/app
    command: ["python", "./ponto_recarga.py"]
    deploy:
      replicas: 400
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
  cliente:
    build: .
    depends_on:
      - nuvem
    environment:
      - DOCKER_ENV=true
      - HOSTNAME=cliente_{{.Task.Slot}}
    networks:
      - rede_recarga
    volumes:
      - .:/app
    command: ["python", "./cliente.py"]
    deploy:
      replicas: 200
      resources:
        limits:
          cpus: '0.05'
          memory: 64M

networks:
  rede_recarga:
    driver: bridge