networks:
  charging_network:
    driver: bridge
services:
  car_1:
    build: .
    command: python -u car.py vehicle_1 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_1
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_10:
    build: .
    command: python -u car.py vehicle_10 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_10
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_11:
    build: .
    command: python -u car.py vehicle_11 normal
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_11
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=normal
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_12:
    build: .
    command: python -u car.py vehicle_12 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_12
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_13:
    build: .
    command: python -u car.py vehicle_13 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_13
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_14:
    build: .
    command: python -u car.py vehicle_14 fast
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_14
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=fast
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_15:
    build: .
    command: python -u car.py vehicle_15 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_15
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_2:
    build: .
    command: python -u car.py vehicle_2 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_2
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_3:
    build: .
    command: python -u car.py vehicle_3 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_3
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_4:
    build: .
    command: python -u car.py vehicle_4 normal
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_4
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=normal
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_5:
    build: .
    command: python -u car.py vehicle_5 normal
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_5
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=normal
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_6:
    build: .
    command: python -u car.py vehicle_6 fast
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_6
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=fast
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_7:
    build: .
    command: python -u car.py vehicle_7 slow
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_7
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=slow
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_8:
    build: .
    command: python -u car.py vehicle_8 fast
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_8
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=fast
    networks:
    - charging_network
    volumes:
    - ./:/app
  car_9:
    build: .
    command: python -u car.py vehicle_9 fast
    depends_on:
    - server_a
    - server_b
    - server_c
    - server_d
    - server_e
    environment:
    - VEHICLE_ID=vehicle_9
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - DISCHARGE_RATE=fast
    networks:
    - charging_network
    volumes:
    - ./:/app
  server_a:
    build: .
    command: python -u server_a.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=a
    networks:
    - charging_network
    ports:
    - 5000:5000
    volumes:
    - ./:/app
  server_b:
    build: .
    command: python -u server_b.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=b
    networks:
    - charging_network
    ports:
    - 5001:5001
    volumes:
    - ./:/app
  server_c:
    build: .
    command: python -u server_c.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=c
    networks:
    - charging_network
    ports:
    - 5002:5002
    volumes:
    - ./:/app
  server_d:
    build: .
    command: python -u server_d.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=d
    networks:
    - charging_network
    ports:
    - 5003:5003
    volumes:
    - ./:/app
  server_e:
    build: .
    command: python -u server_e.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=e
    networks:
    - charging_network
    ports:
    - 5004:5004
    volumes:
    - ./:/app
version: '3.8'
