networks:
  charging_network:
    driver: bridge
services:
  car_1:
    build: .
    command: python car.py vehicle_1 fast
    depends_on:
    - server_a
    - server_b
    - server_c
    environment:
    - VEHICLE_ID=vehicle_1
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    networks:
    - charging_network
    volumes:
    - ./:/app
  server_a:
    build: .
    command: python server_a.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=a
    networks:
    - charging_network
    ports:
    - 5000:5000
    volumes:
    - ./:/app
  server_b:
    build: .
    command: python server_b.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=b
    networks:
    - charging_network
    ports:
    - 5001:5001
    volumes:
    - ./:/app
  server_c:
    build: .
    command: python server_c.py
    environment:
    - FLASK_ENV=development
    - MQTT_BROKER=broker.hivemq.com
    - MQTT_PORT=1883
    - SERVER_NAME=c
    networks:
    - charging_network
    ports:
    - 5002:5002
    volumes:
    - ./:/app
version: '3.8'
